WITH plan_entitlements_seed(
	plan_code,
	feature_key,
	value_bool,
	value_int,
	value_decimal,
	value_string
) AS (
	VALUES
		('free', 'users.max_users', NULL::boolean, 1::bigint, NULL::numeric, NULL::text),
		('free', 'users.invite_user', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'roles.custom_roles', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'landing.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'landing.max_pages', NULL::boolean, 1::bigint, NULL::numeric, NULL::text),
		('free', 'landing.max_sections_per_page', NULL::boolean, 8::bigint, NULL::numeric, NULL::text),
		('free', 'landing.custom_domain', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'landing.remove_branding', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'landing.analytics', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'crm.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'media.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'media.max_storage_mb', NULL::boolean, 100::bigint, NULL::numeric, NULL::text),
		('free', 'media.max_file_size_mb', NULL::boolean, 5::bigint, NULL::numeric, NULL::text),
		('free', 'domain.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'domain.max_custom_domains', NULL::boolean, 0::bigint, NULL::numeric, NULL::text),
		('free', 'whatsapp.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'pos.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'membership.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('free', 'automation.enabled', false, NULL::bigint, NULL::numeric, NULL::text),

		('starter', 'users.max_users', NULL::boolean, 3::bigint, NULL::numeric, NULL::text),
		('starter', 'users.invite_user', true, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'roles.custom_roles', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.max_pages', NULL::boolean, 3::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.max_sections_per_page', NULL::boolean, 16::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.custom_domain', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.remove_branding', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'landing.analytics', true, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'crm.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'crm.max_contacts', NULL::boolean, 500::bigint, NULL::numeric, NULL::text),
		('starter', 'crm.import_export', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'crm.pipeline', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'media.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'media.max_storage_mb', NULL::boolean, 1000::bigint, NULL::numeric, NULL::text),
		('starter', 'media.max_file_size_mb', NULL::boolean, 10::bigint, NULL::numeric, NULL::text),
		('starter', 'domain.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'domain.max_custom_domains', NULL::boolean, 0::bigint, NULL::numeric, NULL::text),
		('starter', 'whatsapp.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'pos.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'membership.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('starter', 'automation.enabled', false, NULL::bigint, NULL::numeric, NULL::text),

		('growth', 'users.max_users', NULL::boolean, 10::bigint, NULL::numeric, NULL::text),
		('growth', 'users.invite_user', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'roles.custom_roles', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.max_pages', NULL::boolean, 10::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.max_sections_per_page', NULL::boolean, 32::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.custom_domain', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.remove_branding', false, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'landing.analytics', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'crm.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'crm.max_contacts', NULL::boolean, 5000::bigint, NULL::numeric, NULL::text),
		('growth', 'crm.import_export', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'crm.pipeline', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'media.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'media.max_storage_mb', NULL::boolean, 5000::bigint, NULL::numeric, NULL::text),
		('growth', 'media.max_file_size_mb', NULL::boolean, 25::bigint, NULL::numeric, NULL::text),
		('growth', 'domain.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'domain.max_custom_domains', NULL::boolean, 1::bigint, NULL::numeric, NULL::text),
		('growth', 'domain.ssl_auto_provision', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'whatsapp.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'whatsapp.max_messages_per_month', NULL::boolean, 1000::bigint, NULL::numeric, NULL::text),
		('growth', 'pos.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'membership.enabled', false, NULL::bigint, NULL::numeric, NULL::text),
		('growth', 'automation.enabled', false, NULL::bigint, NULL::numeric, NULL::text),

		('business', 'users.max_users', NULL::boolean, 25::bigint, NULL::numeric, NULL::text),
		('business', 'users.invite_user', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'roles.custom_roles', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'landing.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'landing.max_pages', NULL::boolean, 50::bigint, NULL::numeric, NULL::text),
		('business', 'landing.max_sections_per_page', NULL::boolean, 64::bigint, NULL::numeric, NULL::text),
		('business', 'landing.custom_domain', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'landing.remove_branding', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'landing.analytics', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'crm.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'crm.max_contacts', NULL::boolean, 25000::bigint, NULL::numeric, NULL::text),
		('business', 'crm.import_export', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'crm.pipeline', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'media.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'media.max_storage_mb', NULL::boolean, 20000::bigint, NULL::numeric, NULL::text),
		('business', 'media.max_file_size_mb', NULL::boolean, 100::bigint, NULL::numeric, NULL::text),
		('business', 'domain.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'domain.max_custom_domains', NULL::boolean, 5::bigint, NULL::numeric, NULL::text),
		('business', 'domain.ssl_auto_provision', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'whatsapp.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'whatsapp.max_messages_per_month', NULL::boolean, 5000::bigint, NULL::numeric, NULL::text),
		('business', 'pos.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'pos.max_products', NULL::boolean, 5000::bigint, NULL::numeric, NULL::text),
		('business', 'membership.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'membership.max_members', NULL::boolean, 25000::bigint, NULL::numeric, NULL::text),
		('business', 'automation.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('business', 'automation.max_runs_per_month', NULL::boolean, 10000::bigint, NULL::numeric, NULL::text),

		('enterprise', 'users.max_users', NULL::boolean, 1000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'users.invite_user', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'roles.custom_roles', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.max_pages', NULL::boolean, 1000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.max_sections_per_page', NULL::boolean, 128::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.custom_domain', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.remove_branding', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'landing.analytics', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'crm.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'crm.max_contacts', NULL::boolean, 1000000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'crm.import_export', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'crm.pipeline', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'media.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'media.max_storage_mb', NULL::boolean, 100000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'media.max_file_size_mb', NULL::boolean, 500::bigint, NULL::numeric, NULL::text),
		('enterprise', 'domain.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'domain.max_custom_domains', NULL::boolean, 100::bigint, NULL::numeric, NULL::text),
		('enterprise', 'domain.ssl_auto_provision', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'whatsapp.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'whatsapp.max_messages_per_month', NULL::boolean, 100000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'pos.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'pos.max_products', NULL::boolean, 100000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'membership.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'membership.max_members', NULL::boolean, 1000000::bigint, NULL::numeric, NULL::text),
		('enterprise', 'automation.enabled', true, NULL::bigint, NULL::numeric, NULL::text),
		('enterprise', 'automation.max_runs_per_month', NULL::boolean, 1000000::bigint, NULL::numeric, NULL::text)
),
plans AS (
	SELECT id, code
	FROM billing_plans
	WHERE deleted_at IS NULL
),
features AS (
	SELECT id, feature_key
	FROM billing_features
)
INSERT INTO billing_plan_entitlements (
	plan_id,
	feature_id,
	value_bool,
	value_int,
	value_decimal,
	value_string,
	limits,
	created_at,
	updated_at
)
SELECT
	plans.id,
	features.id,
	seed.value_bool,
	seed.value_int,
	seed.value_decimal,
	seed.value_string,
	'{}'::jsonb,
	now(),
	now()
FROM plan_entitlements_seed seed
JOIN plans ON plans.code = seed.plan_code
JOIN features ON features.feature_key = seed.feature_key
ON CONFLICT (plan_id, feature_id)
DO UPDATE SET
	value_bool = EXCLUDED.value_bool,
	value_int = EXCLUDED.value_int,
	value_decimal = EXCLUDED.value_decimal,
	value_string = EXCLUDED.value_string,
	limits = EXCLUDED.limits,
	updated_at = now();
