-- WhatsApp channel sessions (WAHA). One row per WAHA session the app created
-- for an organization. See docs/reference-whatsapp.md.
CREATE TABLE IF NOT EXISTS wa_sessions (
	id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	organization_id uuid NOT NULL,
	-- WAHA session name; global on the WAHA server, generated by the backend.
	name varchar(64) NOT NULL,
	display_name varchar(120),
	phone varchar(20),
	push_name varchar(120),
	status varchar(40) NOT NULL DEFAULT 'STOPPED',
	engine varchar(20),
	waha_server_id varchar(50) NOT NULL DEFAULT 'default',
	is_default boolean NOT NULL DEFAULT false,
	purpose varchar(20) NOT NULL DEFAULT 'sales',
	auto_create_lead boolean NOT NULL DEFAULT false,
	last_status_at timestamp without time zone,
	created_by uuid,
	updated_by uuid,
	created_at timestamp without time zone NOT NULL DEFAULT now(),
	updated_at timestamp without time zone NOT NULL DEFAULT now(),
	deleted_at timestamp without time zone,
	CONSTRAINT wa_sessions_organization_id_id_unique UNIQUE (organization_id, id),
	CONSTRAINT wa_sessions_name_unique UNIQUE (name),
	CONSTRAINT wa_sessions_name_format_check CHECK (name ~ '^[a-z0-9_]{3,64}$'),
	CONSTRAINT wa_sessions_status_check CHECK (
		status IN (
			'STOPPED', 'STARTING', 'SCAN_QR_CODE', 'PASSKEY_REQUIRED',
			'PASSKEY_CONFIRMATION_REQUIRED', 'WORKING', 'FAILED'
		)
	),
	CONSTRAINT wa_sessions_purpose_check CHECK (purpose IN ('cs', 'sales', 'notification')),
	CONSTRAINT fk_wa_sessions_organization_id
		FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
	CONSTRAINT fk_wa_sessions_created_by
		FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
	CONSTRAINT fk_wa_sessions_updated_by
		FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);

-- At most one default (non-deleted) session per organization.
CREATE UNIQUE INDEX IF NOT EXISTS uq_wa_sessions_organization_default
	ON wa_sessions(organization_id)
	WHERE is_default AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_wa_sessions_organization_deleted
	ON wa_sessions(organization_id, deleted_at);

SELECT apply_organization_rls('wa_sessions'::regclass);

-- Maps a WAHA session name to its organization. Intentionally NOT under RLS:
-- WAHA webhooks and the reconcile worker arrive without tenant context, and the
-- runtime role has no BYPASSRLS, so they resolve the organization here before
-- opening a tenant-scoped transaction. Only internal webhook/worker
-- repositories read this table; it is never exposed through tenant endpoints.
CREATE TABLE IF NOT EXISTS wa_session_directory (
	session_name varchar(64) PRIMARY KEY,
	organization_id uuid NOT NULL,
	session_id uuid NOT NULL,
	created_at timestamp without time zone NOT NULL DEFAULT now(),
	deleted_at timestamp without time zone,
	CONSTRAINT wa_session_directory_session_id_unique UNIQUE (session_id),
	CONSTRAINT fk_wa_session_directory_session
		FOREIGN KEY (organization_id, session_id) REFERENCES wa_sessions(organization_id, id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_wa_session_directory_active
	ON wa_session_directory(organization_id)
	WHERE deleted_at IS NULL;
