package domain

import (
	"time"

	"zyad.cloud/internal/platform/whatsapp"
)

type SessionStatus string

// Values mirror WAHA's session statuses (wa_sessions_status_check).
const (
	SessionStatusStopped                     SessionStatus = whatsapp.SessionStatusStopped
	SessionStatusStarting                    SessionStatus = whatsapp.SessionStatusStarting
	SessionStatusScanQRCode                  SessionStatus = whatsapp.SessionStatusScanQRCode
	SessionStatusPasskeyRequired             SessionStatus = whatsapp.SessionStatusPasskeyRequired
	SessionStatusPasskeyConfirmationRequired SessionStatus = whatsapp.SessionStatusPasskeyConfirmationRequired
	SessionStatusWorking                     SessionStatus = whatsapp.SessionStatusWorking
	SessionStatusFailed                      SessionStatus = whatsapp.SessionStatusFailed
)

func (s SessionStatus) IsValid() bool {
	switch s {
	case SessionStatusStopped, SessionStatusStarting, SessionStatusScanQRCode,
		SessionStatusPasskeyRequired, SessionStatusPasskeyConfirmationRequired,
		SessionStatusWorking, SessionStatusFailed:
		return true
	default:
		return false
	}
}

type SessionPurpose string

const (
	SessionPurposeCS           SessionPurpose = "cs"
	SessionPurposeSales        SessionPurpose = "sales"
	SessionPurposeNotification SessionPurpose = "notification"
)

func (p SessionPurpose) IsValid() bool {
	switch p {
	case SessionPurposeCS, SessionPurposeSales, SessionPurposeNotification:
		return true
	default:
		return false
	}
}

// Session is an organization's WhatsApp number connected through WAHA.
// Name is the WAHA session name: global on the WAHA server and generated by
// the backend, never accepted from clients.
type Session struct {
	ID             string
	OrganizationID string
	Name           string
	DisplayName    string
	Phone          string
	PushName       string
	Status         SessionStatus
	Engine         string
	WAHAServerID   string
	IsDefault      bool
	Purpose        SessionPurpose
	AutoCreateLead bool
	LastStatusAt   *time.Time
	CreatedBy      string
	UpdatedBy      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

// DirectoryEntry resolves a WAHA session name to its organization without
// tenant context (webhooks, reconcile worker).
type DirectoryEntry struct {
	SessionName    string
	OrganizationID string
	SessionID      string
}
